# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/my_project/COS/2/MIPS_IO/MIPS_IO.cache/wt [current_project]
set_property parent.project_path D:/my_project/COS/2/MIPS_IO/MIPS_IO.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/my_project/COS/2/MIPS_IO/MIPS_IO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/Desktop/testIO.dat
read_verilog -library xil_defaultlib -sv {
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/ALU.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/ALU_adder.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/ALU_dec.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/new/IO.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/control_unit.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/new/dMemoryDecoder.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/data_memory.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/datapath.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/new/digit_led.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/new/getx.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/instruction_memory.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/new/m7seg.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/main_dec.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/mips.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/mux2_32.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/mux2_5.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/pc_plus4.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/program_counter.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/regfile.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/signext.sv
  D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/sources_1/imports/new/mips_top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master_.xdc
set_property used_in_implementation false [get_files D:/my_project/COS/2/MIPS_IO/MIPS_IO.srcs/constrs_1/imports/Downloads/Nexys4DDR_Master_.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mips_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mips_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mips_top_utilization_synth.rpt -pb mips_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
